export enum ScreenId {
  // A. Global
  APP_SHELL = 'APP_SHELL',
  NOTIFICATIONS = 'NOTIFICATIONS',
  
  // B. Onboarding
  WELCOME = 'WELCOME',
  ACCOUNT_CREATION = 'ACCOUNT_CREATION',
  STARTUP_BASICS = 'STARTUP_BASICS',
  INITIAL_READINESS = 'INITIAL_READINESS',
  
  // C. Founders & Equity
  FOUNDERS_LIST = 'FOUNDERS_LIST',
  FOUNDER_PROFILE = 'FOUNDER_PROFILE',
  ALIGNMENT_OVERVIEW = 'ALIGNMENT_OVERVIEW',
  EQUITY_MODELING = 'EQUITY_MODELING',
  SCENARIO_SIMULATOR = 'SCENARIO_SIMULATOR',
  LOCK_ALIGNMENT = 'LOCK_ALIGNMENT',
  ALIGNMENT_HISTORY = 'ALIGNMENT_HISTORY',
  
  // D. AI & Work
  AI_ADVISORS_HOME = 'AI_ADVISORS_HOME',
  AI_ADVISOR_PANEL = 'AI_ADVISOR_PANEL',
  TEAM_EMPLOYEES = 'TEAM_EMPLOYEES',
  AI_EMPLOYEE_DETAIL = 'AI_EMPLOYEE_DETAIL',
  
  // E. Company Intelligence
  COMPANY_DASHBOARD = 'COMPANY_DASHBOARD',
  RELEVANT_CONNECTIONS = 'RELEVANT_CONNECTIONS',
  STAGES_CAPITAL = 'STAGES_CAPITAL',
  
  // F. External Relationships
  INVESTORS_LIST = 'INVESTORS_LIST',
  INVESTOR_DETAIL = 'INVESTOR_DETAIL',
  CUSTOMERS_LIST = 'CUSTOMERS_LIST',
  CUSTOMER_DETAIL = 'CUSTOMER_DETAIL',
  
  // G. Gates
  INCORPORATION_READINESS = 'INCORPORATION_READINESS',
  PROCEED_ANYWAY = 'PROCEED_ANYWAY',
}

export interface NavGroup {
  label: string;
  screens: { id: ScreenId; label: string; icon?: any }[];
}
