import React from 'react';
import { ScreenId } from '../types';
import { Button, Card } from '../components/UI';
import { FileText, Download, FileChartLine, ShieldCheck, ArrowRight } from 'lucide-react';

interface ScreenProps {
    onNavigate: (id: ScreenId) => void;
}

export const DocumentsScreen: React.FC<ScreenProps> = ({ onNavigate }) => {
    const documents = [
        {
            title: "Founder Alignment Report",
            date: "Oct 12, 2025",
            type: "Analysis",
            icon: <ShieldCheck className="text-emerald-500" />,
            size: "1.2 MB"
        },
        {
            title: "Seed Stage Financial Export",
            date: "Nov 01, 2025",
            type: "Financial",
            icon: <FileChartLine className="text-indigo-500" />,
            size: "245 KB"
        },
        {
            title: "Cap Table Snapshot (Pre-Seed)",
            date: "Nov 15, 2025",
            type: "Legal",
            icon: <FileText className="text-blue-500" />,
            size: "890 KB"
        }
    ];

    return (
        <div className="p-8 max-w-4xl mx-auto">
            <header className="mb-10">
                <h2 className="text-4xl font-black text-slate-900 tracking-tight">Documents</h2>
                <p className="text-slate-500 mt-2 font-medium">Critical reports and data exports generated by Foundry.</p>
            </header>

            <div className="space-y-4">
                {documents.map((doc, i) => (
                    <Card key={i} className="p-5 flex items-center justify-between hover:shadow-lg transition-all border-slate-100 group">
                        <div className="flex items-center gap-5">
                            <div className="w-12 h-12 rounded-2xl bg-slate-50 flex items-center justify-center group-hover:bg-white transition-colors">
                                {React.cloneElement(doc.icon as React.ReactElement<any>, { className: "w-6 h-6" })}
                            </div>
                            <div>
                                <h3 className="font-bold text-slate-900 text-lg">{doc.title}</h3>
                                <div className="flex items-center gap-3 mt-1">
                                    <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">{doc.type}</span>
                                    <span className="w-1 h-1 rounded-full bg-slate-300"></span>
                                    <span className="text-xs text-slate-500 font-medium">{doc.date}</span>
                                    <span className="text-xs text-slate-400">• {doc.size}</span>
                                </div>
                            </div>
                        </div>

                        <div className="flex items-center gap-2">
                            <Button variant="secondary" className="px-4 border-slate-200">
                                <Download className="w-4 h-4 mr-2" /> Download
                            </Button>
                            <Button onClick={() => { }} className="bg-slate-900 text-white hover:bg-black">
                                View <ArrowRight className="w-4 h-4 ml-2" />
                            </Button>
                        </div>
                    </Card>
                ))}
            </div>

            <div className="mt-12 p-8 bg-slate-100 rounded-3xl border-2 border-dashed border-slate-200 text-center">
                <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center mx-auto mb-4 shadow-sm">
                    <FileText className="text-slate-400 w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold text-slate-800">Need a custom report?</h3>
                <p className="text-slate-500 mt-2 mb-6 max-w-sm mx-auto">
                    AI can generate specialized analysis on your financials, talent, or market validation.
                </p>
                <Button variant="primary" className="bg-indigo-600 hover:bg-indigo-700 px-8">
                    Generate New Report
                </Button>
            </div>
        </div>
    );
};