import React from 'react';
import { ScreenId } from '../types';
import { Button, Card, Badge } from '../components/UI';
import { FileCheck } from 'lucide-react';

interface ScreenProps {
  onNavigate: (id: ScreenId) => void;
}

export const LockAlignmentScreen: React.FC<ScreenProps> = ({ onNavigate }) => (
  <div className="max-w-3xl mx-auto mt-8 pb-12 p-6">
    <div className="text-center mb-8">
      <div className="mx-auto w-16 h-16 bg-indigo-600 text-white rounded-full flex items-center justify-center mb-4">
        <FileCheck className="w-8 h-8" />
      </div>
      <h2 className="text-3xl font-bold text-slate-900">Lock Alignment</h2>
      <p className="text-slate-500">This version will be hashed and stored as your "Founder Truth".</p>
    </div>

    <Card className="mb-8 border-t-4 border-t-indigo-600">
      <div className="bg-slate-50 p-6 border-b border-slate-200">
        <h3 className="font-serif text-xl font-bold text-slate-800 mb-1">Founder Alignment Summary</h3>
        <p className="text-xs text-slate-500 uppercase tracking-widest">Generated by Foundry AI • {new Date().toLocaleDateString()}</p>
      </div>
      <div className="p-8 space-y-6 font-serif text-slate-800 leading-relaxed">
        <p>
          <strong>1. Equity Split:</strong> The founders agree to a split of <strong>52% (Alex)</strong> and <strong>48% (Jamie)</strong>.
        </p>
        <p>
          <strong>2. Commitment Expectations:</strong> This split is predicated on Alex contributing <strong>60 hours/week</strong> and Jamie contributing <strong>25 hours/week</strong>.
          <span className="bg-amber-100 px-1 rounded mx-1">Note: This disparity is flagged as a high-risk factor.</span>
        </p>
        <p>
          <strong>3. Vesting:</strong> Standard 4-year vesting with a 1-year cliff.
        </p>
        <div className="bg-slate-50 p-4 rounded border border-slate-200 text-sm">
          <strong>Explicit Acknowledgement:</strong>
          <br />
          "We understand that if Jamie leaves immediately after the cliff (12 months), they will retain 12% of the company. We accept this risk."
        </div>
      </div>
      <div className="bg-slate-50 p-6 border-t border-slate-200 flex flex-col sm:flex-row justify-between items-center gap-4">
        <div className="flex gap-4">
          <div className="h-10 w-32 sm:w-40 border-b border-slate-400 relative">
            <span className="absolute -bottom-5 left-0 text-xs text-slate-400">Signed by Alex</span>
          </div>
          <div className="h-10 w-32 sm:w-40 border-b border-slate-400 relative">
            <span className="absolute -bottom-5 left-0 text-xs text-slate-400">Signed by Jamie</span>
          </div>
        </div>
        <Badge color="slate">Draft v1.0</Badge>
      </div>
    </Card>

    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <Button variant="secondary" onClick={() => onNavigate(ScreenId.EQUITY_MODELING)}>Revise Terms</Button>
      <Button variant="black" onClick={() => onNavigate(ScreenId.ALIGNMENT_HISTORY)}>Lock & Generate PDF</Button>
    </div>
  </div>
);